sudo: false
language: node_js
node_js: lts/*
dist: trusty
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
install:
  - travis_retry gem install s3_website -v 3.4.0
  - travis_retry pip install awscli --upgrade --user
  - cd functions && travis_retry npm ci && cd ..
  - cd client && travis_retry npm ci && cd ..
  - cd example-app && travis_retry npm ci && cd ..
script:
  - cd functions && npm run build && npm run test:with-emulator && cd ..
  - cd client && npm run build && cd ..
  - cd example-app && npm run build && cd ..
  - mkdir -p dist/example-app && cp -R example-app/dist/. dist/example-app
after_success:
  - ./s3_deploy.sh
